- hosts: all,!localhost,!dockers
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: reboot all servers
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'
      reboot:
        msg: "Reboot initiated by Ansible"
        connect_timeout: 10
        reboot_timeout: 650
        pre_reboot_delay: 0
        post_reboot_delay: 35
        test_command: whoami

- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: reboot router
      ansible.builtin.shell: ssh opnsense '/sbin/reboot'
      register: output
      changed_when: "'Connection to 10.77.0.1 closed by remote host' in output.stderr"
      failed_when: "'Connection to 10.77.0.1 closed by remote host' not in output.stderr"
    - debug: var=output.stderr_lines

    - name: waiting for router to be rebooted
      ansible.builtin.wait_for:
        host: 10.77.0.1
        port: 22
